# Generated by Django 5.0.2 on 2024-03-05 05:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
