# Generated by Django 5.0.3 on 2024-03-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Email_app', '0007_user_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reset_token',
            new_name='otp_secret',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
